export const INDIAN_BANKS = [
  "State Bank of India",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Canara Bank",
  "Central Bank of India",
  "Indian Bank",
  "Indian Overseas Bank",
  "Punjab National Bank",
  "Punjab & Sind Bank",
  "UCO Bank",
  "Union Bank of India",
  "Axis Bank Ltd.",
  "Bandhan Bank Ltd.",
  "Catholic Syrian Bank Ltd.",
  "City Union Bank Ltd.",
  "DCB Bank Ltd.",
  "Development Credit Bank Ltd.",
  "Dhanlaxmi Bank Ltd.",
  "Federal Bank Ltd.",
  "HDFC Bank Ltd.",
  "ICICI Bank Ltd.",
  "IDBI Bank Ltd.",
  "IDFC FIRST Bank Ltd.",
  "IndusInd Bank Ltd.",
  "Jammu & Kashmir Bank Ltd.",
  "Karnataka Bank Ltd.",
  "Karur Vysya Bank Ltd.",
  "Kotak Mahindra Bank Ltd.",
  "Lakshmi Vilas Bank Ltd.",
  "Nainital Bank Ltd.",
  "Ratnakar Bank Ltd.",
  "RBL Bank Ltd.",
  "South Indian Bank Ltd.",
  "Tamilnad Mercantile Bank Ltd.",
  "YES Bank Ltd.",
  "Slice Bank",
  "AU Small Finance Bank Ltd.",
  "Capital Small Finance Bank Ltd.",
  "Equitas Small Finance Bank Ltd.",
  "ESAF Small Finance Bank Ltd.",
  "Fincare Small Finance Bank Ltd.",
  "Jana Small Finance Bank Ltd.",
  "North East Small Finance Bank Ltd.",
  "Shivalik Small Finance Bank Ltd.",
  "Suryoday Small Finance Bank Ltd.",
  "Ujjivan Small Finance Bank Ltd.",
  "Utkarsh Small Finance Bank Ltd.",
  "Airtel Payments Bank",
  "India Post Payments Bank",
  "Jio Payments Bank",
  "NSDL Payments Bank",
  "Australia and New Zealand Banking Group Ltd.",
  "Abu Dhabi Commercial Bank Ltd.",
  "Bank of Bahrain & Kuwait B.S.C.",
  "Bank of Ceylon",
  "Bank of Nova Scotia",
  "Standard Chartered Bank",
  "Industrial & Commercial Bank of China Ltd.",
  "Mizuho Bank Ltd.",
  "Sumitomo Mitsui Banking Corporation",
  "MUFG Bank Ltd.",
  "Cooperatieve Rabobank U.A.",
  "Qatar National Bank",
  "JSC VTB Bank",
  "Sberbank",
  "United Overseas Bank Ltd.",
  "Shinhan Bank",
  "Woori Bank",
  "KEB Hana Bank",
  "Industrial Bank of Korea",
  "Credit Agricole Corporate & Investment Bank",
  "Citibank N.A.",
  "BNP Paribas",
  "Deutsche Bank",
  "HSBC Ltd.",
  "Andhra Pradesh Grameena Bank",
  "Arunachal Pradesh Rural Bank",
  "Assam Gramin Bank",
  "Bihar Gramin Bank",
  "Chhattisgarh Gramin Bank",
  "Gujarat Gramin Bank",
  "Haryana Gramin Bank",
  "Himachal Pradesh Gramin Bank",
  "Jharkhand Gramin Bank",
  "Karnataka Grameena Bank",
  "Nagaland Rural Bank",
  "Odisha Grameen Bank",
  "Puducherry Grama Bank",
  "Punjab Gramin Bank",
  "Rajasthan Gramin Bank",
  "Tamil Nadu Grama Bank",
  "Telangana Grameena Bank",
  "Tripura Gramin Bank",
  "Uttar Pradesh Gramin Bank",
  "Uttarakhand Gramin Bank",
  "West Bengal Gramin Bank",
] as const;

export type BankName = typeof INDIAN_BANKS[number];
